name:                wordle
version:             0.1.0.0
description:         Explore wordle strategies.
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/wordle.git

extra-source-files:
- README.md

dependencies:
- ansi-terminal
- array
- async
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- containers
- extra
- haskeline
- mtl
- random
- split
- text
- time
- transformers
- word8
- EarleyM

default-extensions:
- BangPatterns
- DeriveFunctor
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        wordle
